service: demo-micro-service
frameworkVersion: '3'

package:
  patterns:
    - "!*.sh"
    - "!.venv/**"
    - "!.eslint*"
    - "!builds/**"
    - "!node_modules/**"
    - "!package-lock.json"
    - "!package.json"
    - "!requirements.txt"
    - "!config/**"
    - "!test/**"
    - "!build.js"
    - "!*.log"
    - "!tests/**"
    - "!README.md"
    - "!serverless/**"

provider:
  name: aws
  runtime: python3.9
  deploymentBucket: vizva-deployment
  environment: # Service wide environment variables
    service: demo-micro-service # creates an environment variable named service with value that follows the property self.service
    stage:  ${self:provider.stage} # creates an environment variable named stage with value that follows the property provider.stage
  profile: ${self:provider.stage}
  region: us-east-1 # e.g. if --stage dev then refers to file config/sls/dev.json and uses the key AWS.Region
  role: arn:aws:iam::374053237961:role/Service-Apex # e.g. if --stage dev then refers to file config/sls/dev.json and uses the key IAM.ARN
  stage: ${opt:stage, 'dev'} #default is dev; one of [dev, stg, prod] ... creates a tag named STAGE with value that follows the CLI OPTION stage

functions:
  # Main API handler
  micro-service-health-check:
    handler: lambdas/health-check.lambda_handler
    description: Main API handler for the data platform microservice
    events:
      - httpApi:
          path: /health
          method: GET
    memorySize: 128
    timeout: 15
    layers:
    - ${cf:demo-core-${self:provider.stage}.DemoCoreLayersExport}