service: demo-core
frameworkVersion: '3'

package:
  patterns:
    - "!*.sh"
    - "!.venv/**"
    - "!.eslint*"
    - "!builds/**"
    - "!node_modules/**"
    - "!package-lock.json"
    - "!package.json"
    - "!requirements.txt"
    - "!config/**"
    - "!test/**"
    - "!build.js"
    - "!*.log"
    - "!tests/**"
    - "!README.md"
    - "!serverless/**"

provider:
  name: aws
  runtime: python3.9
  deploymentBucket: vizva-deployment
  environment: # Service wide environment variables
    service: demo-micro-service # creates an environment variable named service with value that follows the property self.service
    stage:  ${self:provider.stage} # creates an environment variable named stage with value that follows the property provider.stage
  profile: ${self:provider.stage}
  region: us-east-1 # e.g. if --stage dev then refers to file config/sls/dev.json and uses the key AWS.Region
  role: arn:aws:iam::374053237961:role/Service-Apex # e.g. if --stage dev then refers to file config/sls/dev.json and uses the key IAM.ARN
  stage: ${opt:stage, 'dev'} #default is dev; one of [dev, stg, prod] ... creates a tag named STAGE with value that follows the CLI OPTION stage

layers:
  demo_core_layers:
    path: layers
    description: Layers containing common code for Demo data lake services.
    compatibleRuntimes:
      - python3.9

resources:
  Outputs:
    DemoCoreLayersExport:
      Value:
        Ref: DemoUnderscorecoreUnderscorelayersLambdaLayer
      Export:
        Name: DemoUnderscorecoreUnderscorelayersLambdaLayer
      Description: Layer containing common code for Demo data lake services.

plugins:
  - serverless-scriptable-plugin

custom:
  scriptable:
    hooks:
      before:package:cleanup: node ../build-scripts/initialize.js layer ../demo_core/layers/python/demo_core/ && node ../build-scripts/initialize.js glue-library ../demo_core/glue/demo_core/ 1.0.0
      after:deploy:finalize: aws s3 cp demo_core_1.0.0.zip s3://vizva-deployment/glueJobs/glue-libraries/ --profile ${self:provider.stage} && node ../build-scripts/initialize.js remove-layer ../demo_core/layers/ && node ../build-scripts/initialize.js remove-layer ../demo_core/glue/ && node ../build-scripts/initialize.js remove-file demo_core_1.0.0.zip
